# This workflows will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements_dev.txt
        pip install -e .
        Invoke-WebRequest -Uri "https://download.wireguard.com/windows-client/wireguard-installer.exe" -OutFile ".\wireguard-installer.exe"
        Start-Process -FilePath '.\wireguard-installer.exe'
    - name: Lint with flake8
      run: |
        flake8 src
    - name: Lint with mypy
      run: |
        mypy src
    - name: Test with pytest
      run: |
        pytest
    - name: Check paths
      run: |
        ls tests/WireGuard/server_keys
    - name: Check WireGuard
      run: |
        cd tests/WireGuard
        ls .
        ./wg.exe genkey | Tee-Object server_keys/test00_private.key | ./wg.exe pubkey | Tee-Object server_keys/test00_public.key
        ls server_keys
    - name: Try script
      run: |
        python ./src/configs_setup/main.py --path "./tests/WireGuard" --name "test_test"
